INSERT INTO Permissao(Descricao)VALUES('Visualizar usuário')
INSERT INTO Permissao(Descricao)VALUES('Cadastrar usuário')
INSERT INTO Permissao(Descricao)VALUES('Alterar usuário')
INSERT INTO Permissao(Descricao)VALUES('Excluir usuário')
INSERT INTO Permissao(Descricao)VALUES('Visualizar grupo de usuário')
INSERT INTO Permissao(Descricao)VALUES('Cadastrar grupo de usuário')
INSERT INTO Permissao(Descricao)VALUES('Alterar grupo de usuário')
INSERT INTO Permissao(Descricao)VALUES('Excluir grupo de usuário')
INSERT INTO Permissao(Descricao)VALUES('Adicionar permissão a um grupo de usuário')
INSERT INTO Permissao(Descricao)VALUES('Adicionar grupo de usuário a um usuário')
